export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const ADD_PROPERTY = 'ADD_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const ON_CHANGE_FIELD = 'ON_CHANGE_FIELD';
export const GET_PROPERTY_LIST = 'GET_PROPERTY_LIST';
export const SET_PROPERTY_LIST = 'SET_PROPERTY_LIST';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const RESET_DETAILS = 'RESET_DETAILS';

export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
export const CHANGE_FILTER_TEXT = 'CHANGE_FILTER_TEXT';
export const APPLY_FILTER = 'APPLY_FILTER';

export const SET_METRIX_DATA = 'SET_METRIX_DATA';
export const SET_COLUMNS = 'SET_COLUMNS';

export const CHANGE_ADVANCE_FILTER = 'CHANGE_ADVANCE_FILTER';
export const RESET_ADVANCE_FILTER = 'RESET_ADVANCE_FILTER';
export const APPLY_ADVANCE_FILTER = 'APPLY_ADVANCE_FILTER';
export const SET_ADVANCE_FILTER_RESULT = 'SET_ADVANCE_FILTER_RESULT';
