export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const ADD_PROPERTY = 'ADD_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const ON_CHANGE_FIELD = 'ON_CHANGE_FIELD';
export const GET_PROPERTY_LIST = 'GET_PROPERTY_LIST';
