name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  envars:
    description: 'ENVs string'
    required: true
outputs:
  port:
    description: 'PORT'
runs:
  using: 'node12'
  main: 'index.js'
